### ISSUE TITLE
Needs Update

### ISSUE THREAD

**Issue by HeIp** [AmyrAhmady/rn-md-textinput#2]
Update needed to address some new warnings and errors such as:

[Wed Jan 27 2021 12:49:33.500]  ERROR    Warning: Invalid argument supplied to oneOf, expected an array.
[Wed Jan 27 2021 12:49:33.510]  LOG      Running "ReactNative" with {"rootTag":1}
[Wed Jan 27 2021 12:49:33.510]  WARN     Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: %s TextField

**Comment by AmyrAhmady** [comment]
Thank you for opening an issue, it is an old component that was forked from the original repository and I've made a few changes since the old developer wasn't active to merge PRs

I will have to do it in weekend (not this one obviously), and if someone make a PR for it it would be awesome too!
